### ISSUE TITLE
Defect 

### ISSUE THREAD

**Issue by tanujkhator** [tanujkhator/vmcs-before#1]
Data Not Reset after Session completion

**Comment by tanujkhator** [comment]
![defect](https://cloud.githubusercontent.com/assets/11551624/9869392/2917dc12-5bb6-11e5-92ab-e4f3bc52039d.png)

**Comment by proliuxz** [comment]
Bug Fixed, ple check it: https://github.com/tanujkhator/vmcs-before/commit/f6697111f8ad2ac44756fe4e06dd686e8dcb1132

**Comment by achyut92** [comment]
![bug](https://cloud.githubusercontent.com/assets/11267409/9873211/c293c972-5bd0-11e5-8c0d-aa16f104c04a.png)
Hi Tanuj,
    Please check the bug fixes done by the developers and if satisfied close the issue.

**Comment by tanujkhator** [comment]
yeap its done ....thanks team
